apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'expo.modules.gestureexclusion'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.gestureexclusion"
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    compileSdkVersion safeExtGet("compileSdkVersion", 35)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
  }
  lintOptions {
    abortOnError false
  }
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
